1. Import the numpy package under the name np.

In [1]:
import numpy as np

2. Print the numpy version and the configuration.

In [5]:
print(np.__version__)
np.show_config()

1.24.3
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

3. Create a null vector of size 10.

In [6]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array.

In [7]:
Z = np.zeros(10)
print("%d bytes" % (Z.size * Z.itemsize))

80 bytes


5. How to get the documentation of the numpy add function from the command line?

In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

6. Create a null vector of size 10 but the fifth value which is 1.

In [9]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49.

In [10]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last).

In [11]:
Z = np.arange(10, 50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8.

In [12]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0].

In [13]:
Z = np.nonzero([1, 2, 0, 0, 4, 0])
print(Z)

(array([0, 1, 4], dtype=int64),)


11. Create a 3x3 identity matrix.

In [14]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values.

In [15]:
Z = np.random.random((3, 3, 3))
print(Z)

[[[0.3630729  0.17268109 0.41116458]
  [0.30891163 0.15194633 0.47839312]
  [0.8710045  0.01300034 0.48914156]]

 [[0.29052266 0.96046585 0.67341382]
  [0.26634245 0.78171228 0.46224239]
  [0.9063604  0.86770074 0.1250315 ]]

 [[0.24231739 0.40935958 0.7727962 ]
  [0.72047941 0.0826022  0.26871293]
  [0.17526162 0.42207854 0.91202626]]]


13. Create a 10x10 array with random values and find the minimum and maximum values.

In [16]:
Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.02288607790547581 0.999340966853649


14. Create a random vector of size 30 and find the mean value.

In [17]:
Z = np.random.random(30)
Zmean = Z.mean()
print(Zmean)

0.49833184676096715


15. Create a 2d array with 1 on the border and 0 inside.

In [18]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0’s) around an existing array?

In [19]:
Z = np.ones((5, 5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression?

In [20]:
print(0 * np.nan)            # nan
print(np.nan == np.nan)      # False
print(np.inf > np.nan)       # False
print(np.nan - np.nan)       # nan
print(np.nan in set([np.nan])) # True
print(0.3 == 3 * 0.1)        # False

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [21]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern.

In [22]:
Z = np.zeros((8, 8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [23]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


21. Create a checkerboard 8x8 matrix using the tile function.

In [24]:
Z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix.

In [25]:
Z = np.random.random((5, 5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin) / (Zmax - Zmin)
print(Z)

[[0.16198624 0.6552038  0.86909896 0.         0.70530424]
 [0.77948216 0.92651316 0.29194224 0.88737436 0.63570617]
 [0.49290851 0.15558856 0.3714805  0.60744568 0.29906237]
 [0.28603296 0.14079662 0.38265097 1.         0.79019011]
 [0.62605741 0.21603577 0.67064127 0.31222057 0.80663706]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA).

In [26]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\acer\AppData\Local\Temp\ipykernel_23000\295437610.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [27]:
Z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [28]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


26. What is the output of the following script?

In [29]:
# Author: Jake VanderPlas

print(sum(range(5),-1))  # 9
from numpy import *
print(sum(range(5),-1))  # 10

9
10


27. Consider an integer vector Z, which of these expressions are legal?

In [38]:
Z = np.arange(5)
print(Z**Z)      # legal
print(2 << Z >> 2) # legal
print(Z <- Z)    # legal
print(1j*Z)      # legal
print(Z/1/1)     # legal
# print(Z<Z>Z)   # illegal

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


28. What are the result of the following expressions?

In [31]:
print(np.array(0) / np.array(0))           # nan
print(np.array(0) // np.array(0))          # 0
print(np.array([np.nan]).astype(int).astype(float)) # array([-9.22337204e+18])

nan
0
[-2.14748365e+09]


C:\Users\acer\AppData\Local\Temp\ipykernel_23000\3716592554.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))           # nan
C:\Users\acer\AppData\Local\Temp\ipykernel_23000\3716592554.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))          # 0
C:\Users\acer\AppData\Local\Temp\ipykernel_23000\3716592554.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float)) # array([-9.22337204e+18])


29. How to round away from zero a float array ?

In [32]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-2.  4. -7.  4.  2. -7.  1.  7.  1. -7.]


30. How to find common values between two arrays?

In [33]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(np.intersect1d(Z1, Z2))

[2 3 4 5 6 8]


31. How to ignore all numpy warnings (not recommended)?

In [34]:
import warnings
warnings.filterwarnings('ignore')
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

32. Is the following expressions true?

In [35]:
print(np.sqrt(-1) == np.emath.sqrt(-1))  # False

False


33. How to get the dates of yesterday, today and tomorrow?

In [36]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2024-08-18 2024-08-19 2024-08-20
